---
name: hinkskalle
kind: pipeline

concurrency:
  limit: 1

steps:
- name: fetch
  image: drone/git
  commands:
    - git fetch --tags
    - git describe > .tags
- name: testhase
  image: docker.ngs.vbcf.ac.at/flask-base:v1.1.1-1-g89d661f
  environment:
    HINKSKALLE_SETTINGS: ../../conf/config.json
  commands:
  - cd backend
  - pip3 install -e .
  - python3 -m unittest discover -s Hinkskalle/tests/
- name: bauhaus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: dockerauth
    path: /root/.docker
  commands:
  - TAG=$(cat .tags)
  - >
    docker build 
    --label org.label-schema.build-date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    --label org.label-schema.vcs-url="$DRONE_GIT_HTTP_URL"
    --label org.label-schema.vcs-ref="$DRONE_COMMIT_SHA"
    --label at.ac.vbcf.ngs.blame="$DRONE_COMMIT_AUTHOR"
    -t docker.ngs.vbcf.ac.at/hinkskalle:$TAG .
  - docker tag docker.ngs.vbcf.ac.at/hinkskalle:$TAG docker.ngs.vbcf.ac.at/hinkskalle:latest
- name: pushraus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: dockerauth
    path: /root/.docker
  commands:
  - docker push docker.ngs.vbcf.ac.at/hinkskalle
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: dockerauth
  host:
    path: /home/drone/.docker
