---
name: hinkskalle
kind: pipeline

concurrency:
  limit: 1

steps:
- name: fetch
  image: drone/git
  commands:
    - git fetch --tags
    - (git describe || git rev-parse --short HEAD) > .tags
- name: testhase
  image: ghcr.io/csf-ngs/hinkskalle-dev:v2.0.0-tmpfix
  environment:
    HINKSKALLE_SETTINGS: ../../conf/config.json
  commands:
  - cd backend
  - pip3 install -e '.[dev]'
  - nose2
- name: testhase-front
  image: ghcr.io/csf-ngs/hinkskalle-dev:v2.0.0-tmpfix
  commands:
  - cd frontend
  - yarn install
  - yarn test:unit
- name: bauhaus
  depends_on:
  - testhase
  - testhase-front
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - TAG=$(cat .tags)
  - >
    docker build 
    --label org.label-schema.build-date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    --label org.label-schema.vcs-url="$DRONE_GIT_HTTP_URL"
    --label org.label-schema.vcs-ref="$DRONE_COMMIT_SHA"
    --label at.ac.vbcf.ngs.blame="$DRONE_COMMIT_AUTHOR"
    -t ghcr.io/csf-ngs/hinkskalle:$TAG .
- name: reporthinaus
  depends_on:
  - testhase
  - testhase-front
  image: alpine
  volumes:
  - name: assets
    path: /srv
  when:
    status:
      - failure
      - success
    event:
      exclude:
        - pull_request
  commands:
  - mkdir -p /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}
  - cp backend/test_report.html /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/backend-report.html
  - cp frontend/test-report.html /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/frontend-report.html
- name: pickerldrauf
  depends_on:
  - bauhaus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - TAG=$(cat .tags)
  - docker tag ghcr.io/csf-ngs/hinkskalle:$TAG ghcr.io/csf-ngs/hinkskalle:${DRONE_BRANCH=master}
  when:
    event:
      - push
- name: master_pickerldrauf
  depends_on:
  - build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: dockerauth
    path: /root/.docker/config.json
  commands:
  - TAG=$(cat .tags)
  - docker tag ghcr.io/csf-ngs/hinkskalle:$TAG ghcr.io/csf-ngs/hinkskalle:latest
  when:
    branch:
      - master
- name: pushraus
  depends_on:
  - pickerldrauf
  - master_pickerldrauf
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_PASS:
      from_secret: ghcr
    DOCKER_USERNAME:
      from_secret: ghcr-username
  commands:
  - echo "$DOCKER_PASS" | docker login --username $DOCKER_USERNAME --password-stdin
  - docker push ghcr.io/csf-ngs/hinkskalle:latest
  - docker push ghcr.io/csf-ngs/hinkskalle:$(cat .tags)
  - docker push ghcr.io/csf-ngs/hinkskalle:${DRONE_BRANCH=master}
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: assets
  host:
    path: /home/docker/caddy/site/knecht
