---
name: hinkskalle
kind: pipeline

concurrency:
  limit: 1

steps:
- name: fetch
  image: drone/git
  commands:
    - git fetch --tags
    - git describe > .tags
- name: testhase
  image: ghcr.io/csf-ngs/hinkskalle-dev:v2.0.0-tmpfix
  environment:
    HINKSKALLE_SETTINGS: ../../conf/config.json
  commands:
  - cd backend
  - pip3 install -e '.[dev]'
  - nose2
- name: testhase-front
  image: ghcr.io/csf-ngs/hinkskalle-dev:v2.0.0-tmpfix
  commands:
  - cd frontend
  - yarn install
  - yarn test:unit
- name: bauhaus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - >
    docker build 
    --label org.label-schema.build-date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    --label org.label-schema.vcs-url="$DRONE_GIT_HTTP_URL"
    --label org.label-schema.vcs-ref="$DRONE_COMMIT_SHA"
    --label at.ac.vbcf.ngs.blame="$DRONE_COMMIT_AUTHOR"
    -t docker.ngs.vbcf.ac.at/hinkskalle .
- name: reporthinaus
  image: alpine
  volumes:
  - name: assets
    path: /srv
  when:
    status:
      - failure
      - success
    event:
      exclude:
        - pull_request
  command:
  - mkdir -p /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}
  - cp backend/test_report.html /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/backend-report.html
  - cp frontend/test-report.html /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/frontend-report.html
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
