---
name: hinkskalle
kind: pipeline

concurrency:
  limit: 1

steps:
- name: fetch
  image: drone/git
  commands:
    - git fetch --tags
    - git describe > .tags
- name: testhase
  image: ghcr.io/csf-ngs/hinkskalle-dev:v1.1.0
  environment:
    HINKSKALLE_SETTINGS: ../../conf/config.json
  commands:
  - cd backend
  - pip3 install -e '.[dev]'
  - nose2
- name: testhase-front
  image: ghcr.io/csf-ngs/hinkskalle-dev:v1.1.0
  commands:
  - cd frontend
  - yarn install
  - yarn test:unit
- name: bauhaus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: dockerauth
    path: /root/.docker/config.json
  commands:
  - >
    docker build 
    --label org.label-schema.build-date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    --label org.label-schema.vcs-url="$DRONE_GIT_HTTP_URL"
    --label org.label-schema.vcs-ref="$DRONE_COMMIT_SHA"
    --label at.ac.vbcf.ngs.blame="$DRONE_COMMIT_AUTHOR"
    -t docker.ngs.vbcf.ac.at/hinkskalle .
- name: pushraus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: dockerauth
    path: /root/.docker/config.json
  commands:
  - TAG=$(cat .tags)
  - docker tag docker.ngs.vbcf.ac.at/hinkskalle docker.ngs.vbcf.ac.at/hinkskalle:$TAG
  - docker push docker.ngs.vbcf.ac.at/hinkskalle
  - docker tag docker.ngs.vbcf.ac.at/hinkskalle ghcr.io/csf-ngs/hinkskalle:$TAG
  - docker push ghcr.io/csf-ngs/hinkskalle
  when:
    event:
      - tag
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: dockerauth
  host:
    path: /home/docker/drone/docker-config.json
