---
name: hinkskalle
kind: pipeline

concurrency:
  limit: 1

steps:
- name: conformhase
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DEV_VERSION: v2.0.1-tmpfix
    BACKEND_PORT: 17760
    BACKEND_HOST: conformhase
  commands:
    - apk update && apk add docker-compose bash
    - cd share/oci
    - ./conformance-test.sh
- name: testhase
  image: ghcr.io/csf-ngs/hinkskalle-dev:v2.0.1-tmpfix
  environment:
    HINKSKALLE_SETTINGS: ../../conf/config.json
  commands:
  - cd backend
  - pip3 install -e '.[dev]'
  - nose2 --with-coverage
- name: testhase-front
  image: ghcr.io/csf-ngs/hinkskalle-dev:v2.0.1-tmpfix
  commands:
  - cd frontend
  - yarn install
  - yarn test:unit
- name: bauhaus
  depends_on:
  - testhase
  - testhase-front
  - conformhase
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - >
    docker build 
    --label org.label-schema.build-date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    --label org.label-schema.vcs-url="$DRONE_GIT_HTTP_URL"
    --label org.label-schema.vcs-ref="$DRONE_COMMIT_SHA"
    --label at.ac.vbcf.ngs.blame="$DRONE_COMMIT_AUTHOR"
    -t ghcr.io/csf-ngs/hinkskalle:${DRONE_BRANCH=master} .
- name: reporthinaus
  depends_on:
  - testhase
  - testhase-front
  - conformhase
  image: alpine
  volumes:
  - name: assets
    path: /srv
  when:
    status:
      - failure
      - success
    event:
      exclude:
        - pull_request
  commands:
  - mkdir -p /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}
  - cp backend/test_report.html /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/backend-report.html
  - cp -r backend/htmlcov /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/
  - cp frontend/test-report.html /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/frontend-report.html
  - mkdir -p /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/oci
  - cp share/oci/results/{api.log,junit.xml,report.html} /srv/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/oci/
- name: pickerldrauf
  depends_on:
  - bauhaus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - "docker tag ghcr.io/csf-ngs/hinkskalle:${DRONE_BRANCH=master} ghcr.io/csf-ngs/hinkskalle:${DRONE_TAG}"
  - docker tag "ghcr.io/csf-ngs/hinkskalle:${DRONE_BRANCH=master}" "ghcr.io/csf-ngs/hinkskalle:latest"
  when:
    event:
      - tag
- name: pushraus
  depends_on:
  - bauhaus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_PASS:
      from_secret: ghcr
    DOCKER_USERNAME:
      from_secret: ghcr-username
  commands:
  - echo "$DOCKER_PASS" | docker login --username $DOCKER_USERNAME --password-stdin ghcr.io
  - docker push ghcr.io/csf-ngs/hinkskalle:${DRONE_BRANCH=master}
- name: tag_pushraus
  depends_on:
  - pickerldrauf
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_PASS:
      from_secret: ghcr
    DOCKER_USERNAME:
      from_secret: ghcr-username
  commands:
  - echo "$DOCKER_PASS" | docker login --username $DOCKER_USERNAME --password-stdin ghcr.io
  - "docker push ghcr.io/csf-ngs/hinkskalle:${DRONE_TAG}"
  - docker push ghcr.io/csf-ngs/hinkskalle:latest
  when:
    event:
      - tag
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: assets
  host:
    path: /home/docker/caddy/site/knecht
