version: '3'
volumes:
  ldap_db:
  ldap_conf:
services:
  api:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v1.0.0"
    volumes:
      - '.:/srv/hinkskalle/src'
      - './data/sqlite:/data/db'
    command: '../script/start-dev.sh'
    environment:
      PORT: 5000
    env_file:
      - "conf/ldap_secrets.env"
      - "conf/hinkskalle.env"
    ports:
      - '7660:5000'
    working_dir: '/srv/hinkskalle/src/backend'
  rq_worker:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v1.0.0"
    volumes:
      - '.:/srv/hinkskalle/src'
      - './data/sqlite:/data/db'
    command: '../script/start-dev-worker.sh'
    env_file:
      - "conf/ldap_secrets.env"
      - "conf/hinkskalle.env"
    working_dir: '/srv/hinkskalle/src/backend'
  redis:
    image: redis:6-alpine
  ldap:
    image: docker.ngs.vbcf.ac.at/fsk-ldap:v0.1.0
    environment:
      LDAP_LOGIN_DN: cn=login,ou=Adm,dc=ngs,dc=vbcf,dc=ac,dc=at
    env_file:
      - "conf/slapd_secrets.env"
    ports:
      - 389:389
    volumes:
      - ldap_db:/var/lib/ldap/
      - ldap_conf:/etc/ldap/
  build_frontend:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v1.0.0"
    volumes:
      - '.:/srv/hinkskalle/src'
    command: '../script/start-dev-frontend.sh'
    environment:
      VUE_APP_BACKEND_URL: 'http://172.28.128.1:7660/'
      VUE_APP_ENABLE_REGISTER: 'true'
    working_dir: '/srv/hinkskalle/src/frontend'
    depends_on: 
      - api
