version: '3'
services:
  api:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v0.3.3"
    volumes:
      - '.:/srv/hinkskalle/src'
      - './data/sqlite:/data/db'
    command: './script/start.sh'
    environment:
      PORT: 5000
      SQLALCHEMY_DATABASE_URI: 'sqlite:////data/db/hinkskalle.db'
      FSK_URL: 'http://172.28.128.1:6600/fsk3test'
    ports:
      - '7660:5000'
