version: '3'
volumes:
  ldap_db:
  ldap_conf:
  hink_db:
  hockeypuck_db:
  hockeypuck_data:
services:
  api:
    image: "ghcr.io/csf-ngs/hinkskalle-dev:v1.1.1"
    volumes:
      - '.:/srv/hinkskalle/src'
      - './data/sqlite:/data/db'
    command: '../script/start-dev.sh'
    environment:
      PORT: 5000
    env_file:
      - "conf/secrets.env"
      - "conf/hinkskalle.env"
    ports:
      - '7660:5000'
    working_dir: '/srv/hinkskalle/src/backend'
    depends_on:
      - hinkdb
  hinkdb:
    image: postgres:12
    environment:
      POSTGRES_DB: hinkskalle
      POSTGRES_USER: knihskalle
    env_file:
      - "conf/db_secrets.env"
    volumes:
      - hink_db:/var/lib/postgresql/data
  rq_worker:
    image: "ghcr.io/csf-ngs/hinkskalle-dev:v1.1.1"
    command: '../script/start-dev-worker.sh'
    volumes:
      - '.:/srv/hinkskalle/src'
    env_file:
      - "conf/secrets.env"
      - "conf/hinkskalle.env"
    working_dir: '/srv/hinkskalle/src/backend'
    depends_on:
      - redis
      - hinkdb
  redis:
    image: redis:6-alpine
  ldap:
    image: ghcr.io/csf-ngs/fsk-ldap
    environment:
      LDAP_LOGIN_DN: cn=login,ou=Adm,dc=ngs,dc=vbcf,dc=ac,dc=at
    env_file:
      - "conf/slapd_secrets.env"
    ports:
      - 389:389
    volumes:
      - ldap_db:/var/lib/ldap/
      - ldap_conf:/etc/ldap/
  build_frontend:
    image: "ghcr.io/csf-ngs/hinkskalle-dev:v1.1.1"
    volumes:
      - '.:/srv/hinkskalle/src'
    command: '../script/start-dev-frontend.sh'
    environment:
      VUE_APP_BACKEND_URL: 'http://localhost:7660/'
      VUE_APP_ENABLE_REGISTER: 'true'
    working_dir: '/srv/hinkskalle/src/frontend'
    depends_on: 
      - api
  hockeypuck:
    image: "ghcr.io/csf-ngs/hockeypuck"
    ports:
      - "11371:11371"
    depends_on:
      - hockeypuck_db
    volumes:
      - hockeypuck_data:/hockeypuck/data
  hockeypuck_db:
    image: postgres:12
    environment:
      - POSTGRES_USER=hkp
      - POSTGRES_DB=hkp
      - POSTGRES_PASSWORD=hkp
    volumes:
      - hockeypuck_db:/var/lib/postgresql/data
