version: '3'
volumes:
  ldap_db:
  ldap_conf:
services:
  api:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v0.5.0"
    volumes:
      - '.:/srv/hinkskalle/src'
      - './data/sqlite:/data/db'
    command: '../script/start.sh'
    environment:
      PORT: 5000
      LC_ALL: en_US.utf8
      FLASK_APP: Hinkskalle
      SQLALCHEMY_DATABASE_URI: 'sqlite:////data/db/hinkskalle.db'
      HINKSKALLE_SETTINGS: '/srv/hinkskalle/src/conf/config.json'
      HINKSKALLE_LDAP_HOST: ldap
      HINKSKALLE_LDAP_PORT: 389
      HINKSKALLE_LDAP_BIND_DN: cn=login,ou=Adm,dc=ngs,dc=vbcf,dc=ac,dc=at
      HINKSKALLE_LDAP_BASE_DN: ou=Accounts,dc=ngs,dc=vbcf,dc=ac,dc=at
    env_file:
      - "conf/ldap_secrets.env"
    ports:
      - '7660:5000'
    working_dir: '/srv/hinkskalle/src/backend'
  redis:
    image: redis:6-alpine
  ldap:
    image: docker.ngs.vbcf.ac.at/fsk-ldap:v0.1.0
    environment:
      LDAP_LOGIN_DN: cn=login,ou=Adm,dc=ngs,dc=vbcf,dc=ac,dc=at
    env_file:
      - "conf/slapd_secrets.env"
    ports:
      - 389:389
    volumes:
      - ldap_db:/var/lib/ldap/
      - ldap_conf:/etc/ldap/
  build_frontend:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v0.5.0"
    volumes:
      - '.:/srv/hinkskalle/src'
    command: '../script/start-dev-frontend.sh'
    environment:
      VUE_APP_BACKEND_URL: 'http://172.28.128.1:7660'
      VUE_APP_ENABLE_REGISTER: 'true'
    ports:
      - '7661:8080'
    working_dir: '/srv/hinkskalle/src/frontend'
    depends_on: 
      - api
