version: '3'
services:
  api:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v0.4.0"
    volumes:
      - '.:/srv/hinkskalle/src'
      - './data/sqlite:/data/db'
    command: '../script/start.sh'
    environment:
      PORT: 5000
      LC_ALL: en_US.utf8
      FLASK_APP: Hinkskalle
      SQLALCHEMY_DATABASE_URI: 'sqlite:////data/db/hinkskalle.db'
      HINKSKALLE_SETTINGS: '/srv/hinkskalle/src/conf/config.json'
    env_file:
      - "conf/ldap_secrets.env"
    ports:
      - '7660:5000'
    working_dir: '/srv/hinkskalle/src/backend'
  build_frontend:
    image: "docker.ngs.vbcf.ac.at/hinkskalle-dev:v0.4.0"
    volumes:
      - '.:/srv/hinkskalle/src'
    command: '../script/start-dev-frontend.sh'
    ports:
      - '7661:8080'
    working_dir: '/srv/hinkskalle/src/frontend'
    depends_on: 
      - api
