version: '3'
services:
  proxy:
    image: nginx:latest
    volumes:
      - './share/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '7660:80'
  api:
    image: docker.ngs.vbcf.ac.at/hinkskalle-dev
    volumes:
      - '.:/srv/hinkskalle/src'
    command: './script/start.sh'
    environment:
      PORT: 5000
      MONGODB_HOST: 'mongodb://mongodb/hinktest'
      MONGODB_USERNAME: 'hinkebein'
      MONGODB_PASSWORD: "${HINKSKALLE_MONGODB_PASSWORD}"
      FSK_URL: 'http://172.28.128.1:6600/fsk3test'
    links:
      - mongodb
      - proxy
  mongodb:
    image: mongo:4-bionic
    volumes:
      - './data/db:/data/db'
      - './data/configdb:/data/configdb'
