version: 2.1
jobs:
  testmaus-hinten:
    docker:
      - image: ghcr.io/csf-ngs/hinkskalle-dev:v1.2.3
    steps:
      - checkout
      - run:
          name: Testmaus Hinterbau
          command: |
            cd backend
            pip3 install -e '.[dev]'
            nose2
      - store_artifacts:
          path: "backend/test_report.html"
  testmaus-vorn:
    docker:
      - image: ghcr.io/csf-ngs/hinkskalle-dev:v1.2.3
    steps:
      - checkout
      - run:
          name: Testmaus Vorbau
          command: |
            cd frontend
            yarn install
            yarn test:unit
      - store_artifacts:
          path: "frontend/test-report.html"
  machdocker:
    docker: 
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run: 
          name: bauhaus
          command: |
            docker build -t ghcr.io/csf-ngs/hinkskalle .
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: pickerldrauf
                command: |
                  docker tag ghcr.io/csf-ngs/hinkskalle ghcr.io/csf-ngs/hinkskalle:<< pipeline.git.tag >>
            - run:
                name: pushraus
                command: |
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin ghcr.io
                  docker push ghcr.io/csf-ngs/hinkskalle:<< pipeline.git.tag >>
                  docker push ghcr.io/csf-ngs/hinkskalle
workflows:
  version: 2
  alles-raus:
    jobs:
      - testmaus-vorn:
          filters:
            tags: 
              only: /v.*/
      - testmaus-hinten:
          filters:
            tags: 
              only: /v.*/
      - machdocker:
          requires:
            - testmaus-hinten
            - testmaus-vorn
          filters:
            tags:
              only: /v.*/
