version: '3'
services:
  api:
    image: "ghcr.io/csf-ngs/hinkskalle-dev:$DEV_VERSION"
    volumes:
      - '.:/srv/hinkskalle/src'
    command: '../script/start-dev.sh'
    environment:
      PORT: 5000
    env_file:
      - "./share/oci/conf/secrets.env"
      - "./share/oci/conf/hinkskalle.env"
    ports:
      - "$BACKEND_PORT:5000"
    working_dir: '/srv/hinkskalle/src/backend'
    depends_on:
      - hinkdb
  hinkdb:
    image: postgres:12
    environment:
      POSTGRES_DB: hinkskalle
      POSTGRES_USER: knihskalle
    env_file:
      - "conf/db_secrets.env"
