version: "3"
volumes:
  images:
    driver: local
  hink_db:
    driver: local
services:
  api:
    restart: always
    image: ghcr.io/csf-ngs/hinkskalle
    env_file:
      - "conf/secrets.env"
      - "conf/hinkskalle.env"
    environment:
      - PREFERRED_URL_SCHEME=https
    working_dir: '/srv/hinkskalle/backend'
    volumes:
      - ./conf/config.json:/srv/hinkskalle/conf/config.json
      - images:/mnt/images
    ports:
      - '7600:5000'
    depends_on:
      - hinkdb
      - redis
  hinkdb:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_DB: hinkskalle
      POSTGRES_USER: knihskalle
    env_file:
      - "conf/db_secrets.env"
    volumes:
      - hink_db:/var/lib/postgresql/data
  rq_worker:
    image: ghcr.io/csf-ngs/hinkskalle
    command: 'script/start-worker.sh'
    env_file:
      - "conf/secrets.env"
      - "conf/hinkskalle.env"
    depends_on:
      - redis
      - hinkdb
  rq_scheduler:
    image: ghcr.io/csf-ngs/hinkskalle
    command: 'script/start-scheduler.sh'
    env_file:
      - "conf/secrets.env"
      - "conf/hinkskalle.env"
    depends_on:
      - redis
      - hinkdb
  redis:
    image: redis:6-alpine
