"""db cascading delete for upload sessions

Revision ID: 1a080fdf898e
Revises: 34a147e7efb7
Create Date: 2021-06-07 12:41:53.340730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a080fdf898e'
down_revision = '34a147e7efb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_upload_url_parent_id_image_upload_url', 'image_upload_url', type_='foreignkey')
    op.drop_constraint('fk_image_upload_url_image_id_image', 'image_upload_url', type_='foreignkey')
    op.create_foreign_key(op.f('fk_image_upload_url_image_id_image'), 'image_upload_url', 'image', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_image_upload_url_parent_id_image_upload_url'), 'image_upload_url', 'image_upload_url', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_image_upload_url_parent_id_image_upload_url'), 'image_upload_url', type_='foreignkey')
    op.drop_constraint(op.f('fk_image_upload_url_image_id_image'), 'image_upload_url', type_='foreignkey')
    op.create_foreign_key('fk_image_upload_url_image_id_image', 'image_upload_url', 'image', ['image_id'], ['id'])
    op.create_foreign_key('fk_image_upload_url_parent_id_image_upload_url', 'image_upload_url', 'image_upload_url', ['parent_id'], ['id'])
    # ### end Alembic commands ###
