"""quota field

Revision ID: 2800a86f2d6f
Revises: 5961c96f6a2e
Create Date: 2021-06-18 15:52:41.817529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2800a86f2d6f"
down_revision = "5961c96f6a2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("used_quota", sa.BigInteger(), nullable=True))
    op.add_column("collection", sa.Column("used_quota", sa.BigInteger(), nullable=True))
    op.add_column("container", sa.Column("used_quota", sa.BigInteger(), nullable=True))
    conn = op.get_bind()
    if conn.engine.name != "sqlite":
        op.alter_column(table_name="entity", column_name="quota", type_=sa.BigInteger)
    if conn.engine.name == "postgresql":
        conn.execute(sa.text("alter type admkeys add value if not exists 'check_quotas'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "used_quota")
    # ### end Alembic commands ###
