"""group permissions

Revision ID: 2b9677bd1a22
Revises: b819253f1612
Create Date: 2022-04-19 00:05:43.085557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b9677bd1a22"
down_revision = "b819253f1612"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_group",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("admin", "contributor", "readonly", name="group_roles"), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], name=op.f("fk_user_group_group_id_group")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_user_group_user_id_user")),
        sa.PrimaryKeyConstraint("user_id", "group_id", name=op.f("pk_user_group")),
    )
    op.drop_table("users_groups")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_groups",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], name="fk_users_groups_group_id_group"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_users_groups_user_id_user"),
    )
    op.drop_table("user_group")
    # ### end Alembic commands ###
