"""image media type + hide field

Revision ID: 34a147e7efb7
Revises: b12c651bc0db
Create Date: 2021-06-04 15:26:15.421823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34a147e7efb7"
down_revision = "b12c651bc0db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image") as batch_op:
        batch_op.add_column(sa.Column("media_type", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("hide", sa.Boolean(), nullable=True))

    conn = op.get_bind()
    conn.execute(sa.text("UPDATE image SET hide=false"))
    conn.execute(sa.text("UPDATE image SET media_type='application/vnd.sylabs.sif.layer.v1.sif'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("image", "hide")
    op.drop_column("image", "media_type")
    # ### end Alembic commands ###
