"""user quota usage fields

Revision ID: 379ae3b3b0a1
Revises: 87c17a90bc7e
Create Date: 2022-09-18 23:56:37.319625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "379ae3b3b0a1"
down_revision = "87c17a90bc7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("used_quota", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "used_quota")
    # ### end Alembic commands ###
