"""api key hashing

Revision ID: 4d5488f98f01
Revises: c5cd08a2a3fa
Create Date: 2022-05-01 23:27:04.371331

"""
from alembic import op
import sqlalchemy as sa
from passlib.hash import sha512_crypt
from sqlalchemy.sql.expression import text


# revision identifiers, used by Alembic.
revision = '4d5488f98f01'
down_revision = 'c5cd08a2a3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('key_uid', sa.String(), nullable=True))
    op.drop_constraint('uq_token_token', 'token', type_='unique')
    op.create_unique_constraint(op.f('uq_token_key_uid'), 'token', ['key_uid'])
    conn = op.get_bind()
    res = conn.execute("SELECT id, token FROM token")
    for row in res.fetchall():
      key_uid = row[1][:12]
      token = sha512_crypt.hash(row[1], rounds=10000)
      upd = conn.execute(text('UPDATE token SET key_uid=:key_uid, token=:token WHERE id=:id'),
        id=row[0], key_uid=key_uid, token=token)

    op.alter_column('token', 'key_uid', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_token_key_uid'), 'token', type_='unique')
    op.create_unique_constraint('uq_token_token', 'token', ['token'])
    op.drop_column('token', 'key_uid')
    # ### end Alembic commands ###
