"""remove tag image_id not null

Revision ID: 5961c96f6a2e
Revises: 7de1aad1a0ed
Create Date: 2021-06-11 19:42:36.870527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5961c96f6a2e'
down_revision = '7de1aad1a0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag') as batch_op:
      batch_op.alter_column('image_id',
                existing_type=sa.INTEGER(),
                nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
