"""current signature counter field

Revision ID: 5fcba8a29da4
Revises: 2b986597b84a
Create Date: 2022-10-07 22:07:24.894046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcba8a29da4'
down_revision = '2b986597b84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pass_key', sa.Column('current_sign_count', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pass_key', 'current_sign_count')
    # ### end Alembic commands ###
