"""more signature fields

Revision ID: 95690d82cbf2
Revises: 0c261701d9cc
Create Date: 2021-01-05 13:42:19.253713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95690d82cbf2'
down_revision = '0c261701d9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signatureVerified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('signatureVerified')

    # ### end Alembic commands ###
