"""token fields

Revision ID: b25abf5d5f0a
Revises: c4577b8a9c60
Create Date: 2020-11-10 16:59:32.156873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25abf5d5f0a'
down_revision = 'c4577b8a9c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    new_type = sa.Enum('auto', 'manual', name='token_source_types')
    new_type.create(op.get_bind())
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expiresAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source', new_type, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('expiresAt')
        batch_op.drop_column('deleted')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
