"""need more upload states for images

Revision ID: b819253f1612
Revises: ffb4b4703369
Create Date: 2022-03-24 22:14:17.418857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b819253f1612'
down_revision = 'ffb4b4703369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('uploadState', sa.Enum('initialized', 'uploading', 'uploaded', 'failed', 'broken', 'completed', name='upload_state_types'), nullable=True))
    conn = op.get_bind()
    if conn.engine.name == 'postgresql':
      conn.execute(sa.text("alter type upload_state_types add value if not exists 'broken'"))
      conn.execute(sa.text("update image set \"uploadState\"=case when uploaded then 'completed'::upload_state_types else 'initialized'::upload_state_types end"))
    else:
      conn.execute(sa.text("update image set \"uploadState\"=case when uploaded then 'completed' else 'initialized' end"))
    op.drop_column('image', 'uploaded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('uploaded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    conn.execute(sa.text("update image set uploaded=case when \"uploadState\"='completed' then true else false end"))
    op.drop_column('image', 'uploadState')
    # ### end Alembic commands ###
