"""group description

Revision ID: c5cd08a2a3fa
Revises: f7aa17526afa
Create Date: 2022-04-28 15:11:17.472951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cd08a2a3fa'
down_revision = 'f7aa17526afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('uq_group_email', 'group', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_group_email', 'group', ['email'])
    op.drop_column('group', 'description')
    # ### end Alembic commands ###
