"""manifests table

Revision ID: ceeba2104da1
Revises: 176eef8ffb6a
Create Date: 2021-05-31 14:56:52.382454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ceeba2104da1"
down_revision = "176eef8ffb6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manifest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=True),
        sa.Column("createdBy", sa.String(), nullable=True),
        sa.Column("updatedAt", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["createdBy"], ["user.username"], name=op.f("fk_manifest_createdBy_user")),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], name=op.f("fk_manifest_image_id_image")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manifest")),
        sa.UniqueConstraint("hash", name=op.f("uq_manifest_hash")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manifest")
    # ### end Alembic commands ###
