"""download timestamp

Revision ID: de8fb907b4dd
Revises: b63bba1322d5
Create Date: 2021-07-16 11:56:39.386807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de8fb907b4dd"
down_revision = "b63bba1322d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("container", sa.Column("latestDownload", sa.DateTime(), nullable=True))
    op.add_column("image", sa.Column("latestDownload", sa.DateTime(), nullable=True))
    op.add_column("manifest", sa.Column("latestDownload", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manifest", "latestDownload")
    op.drop_column("image", "latestDownload")
    op.drop_column("container", "latestDownload")
    # ### end Alembic commands ###
