"""hang manifests to tags

Revision ID: ff9569b2a175
Revises: ceeba2104da1
Create Date: 2021-06-02 19:54:13.520069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff9569b2a175"
down_revision = "ceeba2104da1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM manifest"))
    with op.batch_alter_table("manifest") as batch_op:
        batch_op.add_column(sa.Column("tag_id", sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(op.f("uq_manifest_tag_id"), ["tag_id"])
        batch_op.drop_constraint("fk_manifest_image_id_image", type_="foreignkey")
        batch_op.create_foreign_key(op.f("fk_manifest_tag_id_tag"), "tag", ["tag_id"], ["id"])
        batch_op.drop_column("image_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manifest") as batch_op:
        batch_op.add_column(sa.Column("image_id", sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(op.f("fk_manifest_tag_id_tag"), type_="foreignkey")
        batch_op.create_foreign_key("fk_manifest_image_id_image", "image", ["image_id"], ["id"])
        batch_op.drop_constraint(op.f("uq_manifest_tag_id"), type_="unique")
        batch_op.drop_column("tag_id")
    # ### end Alembic commands ###
