"""hang manifests to tags

Revision ID: ff9569b2a175
Revises: ceeba2104da1
Create Date: 2021-06-02 19:54:13.520069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9569b2a175'
down_revision = 'ceeba2104da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM manifest"))
    op.add_column('manifest', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_manifest_tag_id'), 'manifest', ['tag_id'])
    op.drop_constraint('fk_manifest_image_id_image', 'manifest', type_='foreignkey')
    op.create_foreign_key(op.f('fk_manifest_tag_id_tag'), 'manifest', 'tag', ['tag_id'], ['id'])
    op.drop_column('manifest', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manifest', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_manifest_tag_id_tag'), 'manifest', type_='foreignkey')
    op.create_foreign_key('fk_manifest_image_id_image', 'manifest', 'image', ['image_id'], ['id'])
    op.drop_constraint(op.f('uq_manifest_tag_id'), 'manifest', type_='unique')
    op.drop_column('manifest', 'tag_id')
    # ### end Alembic commands ###
