"""image expiration

Revision ID: ffb4b4703369
Revises: de8fb907b4dd
Create Date: 2021-07-20 21:24:50.335958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb4b4703369'
down_revision = 'de8fb907b4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('expiresAt', sa.DateTime(), nullable=True))
    conn = op.get_bind()
    if conn.engine.name == 'postgresql':
      conn.execute(sa.text("alter type admkeys add value if not exists 'expire_images'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'expiresAt')
    # ### end Alembic commands ###
